spring.application.name=pro-emsalud-laboratory-api

spring.datasource.url=jdbc:mysql://localhost:3306/pro_emsalud_laboratory
spring.datasource.username=root
spring.datasource.password=sasa

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
